### ISSUE TITLE
UCI protocol

### ISSUE THREAD

**Issue by AlexBrunetti** [pedromonteir1111/rust-chess-engine#1]
Hi,
congrats, the engine works fine, not superstrong but sufficient to fight vs players up to 2000 Elo.

Have you ever considered implementing the UCI protocol so that it can be tested against other programs? Here you can find all the details: https://www.chessprogramming.org/Main_Page

Thanks,
Alex

**Comment by pedromonteir1111** [comment]
Hello Alex,
Thank you so much for trying out my engine and giving feedback!

I started this simple chess engine for a search algorithm assignment from my university and to learn rust as well. I've taken a look into the link you shared and it would be a great addition indeed! Although I also have other features in mind, I don't know if i'll keep working on this project in the near feature, since I'm done with it's original purpose. But if get back to it, I sure will try to implement it.

Best regards,
Pedro
